abbrevations = ['AAA', 'AAS', 'ABCD syndrome', 'ACC', 'ACS', 'ACTH deficiency', 'AD', 'AD', 'ADD', 'ADD-RT', 'ADEM', 'ADHD', 'AERD',
 'AF', 'AGS', 'AHC', 'AHF', 'AIDS', 'AIP', 'ALA DD', 'ALD', 'ALI', 'ALL', 'ALS', 'AMD', 'AML', 'AODM', 'AOS', 'APA',
 'APS', 'ARBD', 'ARD', 'ARDS', 'ARND', 'AS', 'AS', 'ASCVD', 'ASD', 'ASDs', 'ASS', 'A-T', 'AVMs', 'BA', 'BBS', 'BEB',
 'BD', 'BEH', 'BH', 'BMD', 'BPAD', 'BPD', 'BPH', 'BS', 'BSE', 'BSS', 'BV', 'CA', 'CACH', 'CAD', 'CADASIL', 'CAPD',
 'CCD', 'CCHF', 'CCHS', 'CCM', 'CDG', 'CDGS', 'CEP', 'CESD', 'CF', 'CFIDS', 'CFS', 'CGBD', 'CH', 'CHARGE syndrome',
 'CHD', 'CHD', 'CHD', 'CHF', 'CIDP', 'CIPA', 'CIP', 'CJD', 'CKD', 'CML', 'CMs', 'CMT disease', 'COFS', 'COLD', 'COPD',
 'COVID-19', 'CP', 'CP', 'CPPS', 'CPDD', 'CPM', 'CPPS', 'CRE', 'CRF', 'CRKP', 'CRPS', 'CSA', 'CSD', 'CTE', 'CTF', 'CVD',
 'CWD', 'DAS', 'DBA', 'DBMD', 'DD', 'DEF', 'DF', 'DH', 'DHF', 'DHPR', 'DI', 'DiG', 'DISH', 'DJD', 'DLB', 'DM', 'DMD',
 'DP', 'DPT', 'DRSP disease', 'DS', 'DSPS', 'DTs', 'DVD', 'DVT', 'ED', 'ED', 'EDS', 'EDS', 'EEE', 'EHK', 'EMH', 'EMR',
 'ENS', 'EPM', 'EPP', 'ESRD', 'ESS', 'EVD', 'FAE', 'FAS', 'FASDs', 'FFI', 'FMA', 'FMD', 'FMS', 'FSP', 'FTD', 'FUO',
 'FVS', 'Fx', 'FXS', 'GAD', 'GAN', 'GAS disease', 'GBS', 'GBS disease', 'GCE', 'GD', 'GERD', 'GI', 'GIB', 'GN',
 'GSS disease', 'GT', 'LD', 'GVHD', 'GWD', 'H1N1 flu', 'HAS', 'HCP', 'HD', 'HDL2', 'HELLP syndrome', 'HeV Infection',
 'HFA', 'HFMD', 'HFRS', 'HI', 'HiB disease', 'HIBM', 'HMSN Type III', 'HOH', 'HTN', 'HPRT deficiency', 'HPS',
 'HPV Infection', 'HSP', 'IBD', 'IBIDS syndrome', 'IBM', 'IBS', 'IBS', 'IC', 'PBS', 'ICF syndrome', 'ID', 'IED',
 'IFAP syndrome', 'IHA', 'INAD', 'IP', 'IRD', 'IS', 'ITP', 'JAS', 'JE', 'JHD', 'JODM', 'JRA', 'KFD', 'KS', 'KSS', 'KTS',
 'KTW Syndrome', 'LCM', 'LD', 'LD', 'LEMS', 'LFA', 'LGV', 'LKS', 'LNS', 'LP', 'LP', 'LUHF', 'MAC', 'MBD', 'MCS', 'MD',
 'MDS', 'MDD', 'MDR TB', 'ME', 'MERS', 'MI', 'MID', 'MJD', 'ML', 'MLD', 'MMA', 'MMR', 'MMRV', 'MND', 'MODY', 'MOH',
 'MPD', 'MPS I', 'MPS II', 'MPS III', 'MPS IV', 'MPS VI', 'MPS VII', 'MR', 'DD', 'MS', 'MSA', 'MSDD', 'NAS', 'NBIA',
 'NCIP', 'NCL', 'NF1', 'NF2', 'NKH', 'NLD', 'NMDs', 'NMO', 'NMS', 'NP', 'NPC1', 'NPH', 'NTD', 'NTDs', 'NTDs', 'OA',
 'OCD', 'ODD', 'OHF', 'OMA', 'ON', 'OPC', 'OPCA', 'OSA', 'PBC', 'PBD', 'PCOS', 'PCT', 'PD', 'PDD', 'PDD-NOS', 'PDD',
 'NOS', 'PE', 'PKAN', 'PLMD', 'PLS', 'PMD', 'PML', 'PMS', 'POTS', 'PPMA', 'PPS', 'PSC', 'PSP', 'PVL', 'PW', 'Q fever',
 'QPD', 'QPS', 'RA', 'RAD', 'RIND', 'RLF', 'RLS', 'RMDs', 'ROP', 'RS', 'RSD', 'RTI', 'RVF', 'SARS', 'SB', 'SBMD', 'SBS',
 'SC', 'SD', 'SDD', 'SIDS', 'SIRS', 'SIS', 'SLE', 'SM', 'SMA', 'SMD', 'SMEI', 'SMS', 'SOD', 'SPD', 'SPS', 'SSPE',
 'STEMI', 'STD', 'SUNCT', 'SWS', 'TAC', 'TB', 'TBI', 'TCS', 'TEF', 'TIA', 'TMH', 'TMJ', 'TMD', 'TMR', 'TN', 'TOS', 'TS',
 'TS', 'TSC', 'TSEs', 'TSP', 'TTH', 'TTP', 'UCPPS', 'UDA', 'UTI', 'UC', 'URI', 'VCFS', 'vCJD', 'VD', 'VHF', 'VHL', 'VP',
 'VSD', 'VVC', 'VWD', 'VWM disease', 'WAGR syndrome', 'WD', 'WEE', 'WS', 'X-ALD', 'X-CALD',
 'XDH and AOX dual deficiency', 'XDH deficiency', 'XDP', 'XDR TB', 'XHED', 'XLSA', 'XMEN', 'XP', 'XSCID',
 'XXX syndrome', 'YF', 'YNS', 'YSS', 'YVS', 'YY syndrome', 'ZAP-70 deficiency', 'ZBLS', 'ZES', 'ZLS', 'ZS',
 'ZTTK syndrome']
